"""create waiting_list_users

Revision ID: 4ae819736523
Revises: 
Create Date: 2026-02-23 22:17:41.799703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae819736523'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_list_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_list_users_email'), 'waiting_list_users', ['email'], unique=True)
    op.create_index(op.f('ix_waiting_list_users_id'), 'waiting_list_users', ['id'], unique=False)
    op.create_index(op.f('ix_waiting_list_users_phone_number'), 'waiting_list_users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_waiting_list_users_referral_code'), 'waiting_list_users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_list_users_referral_code'), table_name='waiting_list_users')
    op.drop_index(op.f('ix_waiting_list_users_phone_number'), table_name='waiting_list_users')
    op.drop_index(op.f('ix_waiting_list_users_id'), table_name='waiting_list_users')
    op.drop_index(op.f('ix_waiting_list_users_email'), table_name='waiting_list_users')
    op.drop_table('waiting_list_users')
    # ### end Alembic commands ###
